[formatting]
allowed_blank_lines = 1
array_auto_collapse = true
array_auto_expand = false
column_width = 360
compact_arrays = true
compact_entries = false
compact_inline_tables = false
crlf = false
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true
